package tz.co.asoft

fun Appender.d(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.DEBUG, msg = msg, data = *data)
fun Appender.i(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.INFO, msg = msg, data = *data)
fun Appender.w(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.WARNING, msg = msg, data = *data)
fun Appender.e(msg: String, c: Throwable?, vararg data: Pair<String, Any?>) = append(level = LogLevel.ERROR, msg = msg, data = *data)
fun Appender.f(msg: String, c: Throwable?, vararg data: Pair<String, Any?>) = append(level = LogLevel.FAILURE, msg = msg, data = *data)
fun Appender.e(msg: String, vararg data: Pair<String, Any?>) = e(msg, null, data = *data)
fun Appender.e(c: Throwable?) = e(c?.message ?: "Unknown Error", c)
fun Appender.f(msg: String, vararg data: Pair<String, Any?>) = f(msg, null, data = *data)
fun Appender.f(c: Throwable?) = f(c?.message ?: "Unknown Error", c)

fun Appender.log(o: Any?) = obj(o)
fun Appender.log(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.DEBUG, msg = msg, data = *data)
fun Appender.debug(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.DEBUG, msg = msg, data = *data)
fun Appender.info(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.INFO, msg = msg, data = *data)
fun Appender.warn(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.WARNING, msg = msg, data = *data)
fun Appender.error(msg: String, c: Throwable?, vararg data: Pair<String, Any?>) = append(level = LogLevel.ERROR, msg = msg, data = *data)
fun Appender.error(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.ERROR, msg = msg, data = *data)
fun Appender.error(c: Throwable?) = e(c?.message ?: "Unknown Error", c)
fun Appender.failure(msg: String, c: Throwable?, vararg data: Pair<String, Any?>) = append(level = LogLevel.FAILURE, msg = msg, data = *data)
fun Appender.failure(msg: String, vararg data: Pair<String, Any?>) = append(level = LogLevel.FAILURE, msg = msg, data = *data)
fun Appender.failure(c: Throwable?) = f(c?.message ?: "Unknown Error", c)
fun Appender.obj(vararg obj: Any?) = append(*obj)